#ifndef FINAL_MODULE_SEGMENTER_INCLUDE_API_SEGMENTER_SEGMENTER_STD_HPP_INCLUDED
#define FINAL_MODULE_SEGMENTER_INCLUDE_API_SEGMENTER_SEGMENTER_STD_HPP_INCLUDED
namespace api {
namespace segmenter {

class segmenter_std {
    
};

} // namespace segmenter
} // namespace api

#endif // FINAL_MODULE_SEGMENTER_INCLUDE_API_SEGMENTER_SEGMENTER_STD_HPP_INCLUDED
